# build stage
FROM --platform=linux/amd64 node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG BACKEND_URL
ENV VITE_BACKEND_URL=$BACKEND_URL
ARG COSY_DEVICE_URL_1
ENV VITE_COSY_DEVICE_URL_1=$COSY_DEVICE_URL_1
ARG COSY_DEVICE_LABEL_1
ENV VITE_COSY_DEVICE_LABEL_1=$COSY_DEVICE_LABEL_1
ARG COSY_DEVICE_URL_2
ENV VITE_COSY_DEVICE_URL_2=$COSY_DEVICE_URL_2
ARG COSY_DEVICE_LABEL_2
ENV VITE_COSY_DEVICE_LABEL_2=$COSY_DEVICE_LABEL_2
ARG COSY_DEVICE_URL_3
ENV VITE_COSY_DEVICE_URL_3=$COSY_DEVICE_URL_3
ARG COSY_DEVICE_LABEL_3
ENV VITE_COSY_DEVICE_LABEL_3=$COSY_DEVICE_LABEL_3
RUN echo "VITE_BACKEND_URL=$VITE_BACKEND_URL, VITE_COSY_DEVICE_URL_1=$VITE_COSY_DEVICE_URL_1, VITE_COSY_DEVICE_LABEL_1=$VITE_COSY_DEVICE_LABEL_1, VITE_COSY_DEVICE_URL_2=$VITE_COSY_DEVICE_URL_2, VITE_COSY_DEVICE_LABEL_2=$VITE_COSY_DEVICE_LABEL_2, VITE_COSY_DEVICE_URL_3=$VITE_COSY_DEVICE_URL_3, VITE_COSY_DEVICE_LABEL_3=$VITE_COSY_DEVICE_LABEL_3"
RUN npm run build

# production stage
FROM --platform=linux/amd64 steebchen/nginx-spa:stable as production-stage
COPY --from=build-stage /app/dist/ /app
CMD ["nginx"]